version: 2


sources:
  - name: staging
    description: "Contains data staged for transformation (ELT)"
    database: eighth-beacon-357016
    schema: trips_data_all
    tables:
      - name: green_tripdata
        description: "Staging table for the green taxi transformation"
        columns:
          - name: VendorID 
            description: "Vendor ID"
      - name: yellow_tripdata
        description: "Staging table for the green taxi transformation"
        columns:
          - name: VendorID 
            description: "Vendor ID"
 